      ******************************************************************
      * Created: Mon, 27 Nov 2023 09:43:25 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: Motor-policy-average
      * Workbook id: 2ca16d9f-cda7-4c68-9b38-46b1216f5242
      * Project: $GenApp_0f349e82-bf83-4635-ac8d-7b5190e94cc7
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. GETMAVG.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
      * PATH : .../Cobol Programs/GETAAVG.cbl
       01 WS-SWITCHES.
          05 WS-CUSTOMER-EXISTS  PIC X(01)  VALUE 'N'.
             88 VALID-CUSTOMER              VALUE 'Y'.
             88 INVALID-CUSTOMER            VALUE 'N'.
       01 WS-WORK.
          05 WS-AVG-PREMIUM      PIC S9(09) COMP.
          05 WS-CUSTOMER-NUMBER  PIC S9(09) COMP.
          05 WS-STATUS-CODE      PIC X(02)  VALUE SPACES.
        01 WS-IN-REC.
           05 OUT-PREMIUM         PIC 9(09).
           05 IN-REQUEST-ID       PIC X(06).
           05 IN-CUST-NUMBER      PIC 9(10).
           05 IN-OVERPAID-FLAG    PIC X(01).
      ******************************************************************
        COPY SQLCA.
      * PATH : .../Copybooks/SQLCA.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      * 01 SQLCA.
      *     05 SQLCODE     PIC S9(9) COMP-5.
      ******************************************************************

      * SQLCA DB2 communications area
           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
       MAINLINE-PARA.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 90
      * STMT END LINE NUMBER : 94
           INITIALIZE WS-SWITCHES

           DISPLAY "CUSTOMER NUMBER IS " IN-CUST-NUMBER
           MOVE IN-CUST-NUMBER TO WS-CUSTOMER-NUMBER
           .
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 106
      * STMT END LINE NUMBER : 108
      *    WHEN '0AVMOT'
                PERFORM 3100-GET-AVG-MOT-PREMIUM
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                   THRU 3100-EXIT.
              PERFORM 9000-END-PARA.
       MAINLINE-PARA-EXIT.
           EXIT.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 339
      * STMT END LINE NUMBER : 379
       3100-GET-AVG-MOT-PREMIUM.

           PERFORM 310A-VALIDATE-CUSTOMER
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
              THRU 310A-EXIT

           IF VALID-CUSTOMER

              EXEC SQL
                 SELECT AVG(MOT.PREMIUM)
                 INTO :WS-AVG-PREMIUM
                 FROM CUSTOMER CUST
                 INNER JOIN POLICY POL
                 ON POL.CUSTOMERNUMBER = CUST.CUSTOMERNUMBER
                 INNER JOIN MOTOR MOT
                 ON POL.POLICYNUMBER = MOT.POLICYNUMBER
                 WHERE POL.CUSTOMERNUMBER = :WS-CUSTOMER-NUMBER
                 GROUP BY POL.CUSTOMERNUMBER
              END-EXEC

              DISPLAY 'SQLCODE:' SQLCODE

              EVALUATE SQLCODE
               WHEN 0
                    MOVE '00' TO WS-STATUS-CODE
               WHEN 100
                    MOVE '02' TO WS-STATUS-CODE
                    PERFORM 9000-END-PARA
               WHEN OTHER
                    MOVE '16' TO WS-STATUS-CODE
                    PERFORM 9000-END-PARA
              END-EVALUATE
           ELSE
              MOVE '08' TO WS-STATUS-CODE
              DISPLAY 'INVALID CUSTOMER!!!'
              PERFORM 9000-END-PARA
           END-IF

           PERFORM 4000-CHECK-IF-OVERPAID
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
              THRU 4000-EXIT

           .
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 380
      * STMT END LINE NUMBER : 381
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
       3100-EXIT.
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           EXIT.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 383
      * STMT END LINE NUMBER : 404
       310A-VALIDATE-CUSTOMER.

           EXEC SQL
                SELECT CUSTOMERNUMBER
                INTO :WS-CUSTOMER-NUMBER
                FROM CUSTOMER
                WHERE CUSTOMERNUMBER = :WS-CUSTOMER-NUMBER
           END-EXEC

           DISPLAY 'SQLCODE:' SQLCODE

           EVALUATE SQLCODE
           WHEN 0
                SET VALID-CUSTOMER   TO TRUE
                DISPLAY 'VALID'
           WHEN 100
                SET INVALID-CUSTOMER TO TRUE
           WHEN OTHER
                MOVE '16' TO WS-STATUS-CODE
                PERFORM 9000-END-PARA
           END-EVALUATE
           .
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 406
      * STMT END LINE NUMBER : 407
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
       310A-EXIT.
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           EXIT.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 505
      * STMT END LINE NUMBER : 518
       4000-CHECK-IF-OVERPAID.

      *    Missing numeric check
           EVALUATE IN-REQUEST-ID

             WHEN '0AVMOT'
               PERFORM 4100-CALC-RETURN-PREMIUM
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                  THRU 4100-EXIT

             WHEN OTHER
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
               CONTINUE

           END-EVALUATE
           .
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 520
      * STMT END LINE NUMBER : 521
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
       4000-EXIT.
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           EXIT.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 523
      * STMT END LINE NUMBER : 531
       4100-CALC-RETURN-PREMIUM.

           IF IN-OVERPAID-FLAG = 'Y'
              COMPUTE OUT-PREMIUM = WS-AVG-PREMIUM * -1
           ELSE
              MOVE WS-AVG-PREMIUM TO OUT-PREMIUM
           END-IF
           DISPLAY 'PREMIUM GETAAVG:' OUT-PREMIUM
           .
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 533
      * STMT END LINE NUMBER : 534
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
       4100-EXIT.
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           EXIT.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:GETAAVG
      * PROGRAM PATH : .../Cobol Programs/GETAAVG.cbl
      * STMT START LINE NUMBER : 536
      * STMT END LINE NUMBER : 540
       9000-END-PARA.

           DISPLAY 'STATUS CODE:' WS-STATUS-CODE

      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           GOBACK.
      ******************************************************************
           EXIT PROGRAM.
